const fs = require('fs');
let c = fs.readFileSync('src/data/aiTools.ts', 'utf8');

c = c.replace(/export const aiTools: AITool\[\] = \[/, `export const aiTools: AITool[] = [
  {
    slug: 'nano-ai',
    name: '纳米AI搜索',
    company: '360',
    officialUrl: 'https://bot.n.cn',
    category: 'search',
    categories: ['search', 'chat'],
    region: 'china',
    shortDescription: '360推出的多模态AI搜索引擎，提供精准快速的信息获取体验。',
    description: '纳米AI搜索是360集团推出的一款多模态AI搜索引擎，集成了搜索、阅读、写作和创作等多种功能。它不仅能提供传统的搜索结果，还通过接入多家大模型，具备深度推理、视频/PPT生成以及多智能体协同能力。',
    tags: ['AI搜索', '360', '多模态', '大模型'],
    featured: false,
    freePlan: 'yes',
    pricingType: 'freemium',
    chineseSupport: 'native',
    accountRequired: 'yes',
    platforms: ['web', 'windows', 'mac', 'ios', 'android'],
    bestFor: '需要高效检索中文信息、分析文档和创作内容的用户',
    lastUpdated: '2026-09-15',
    seoTitle: '纳米AI搜索：360官方多模态AI引擎使用指南与入口',
    seoDescription: '了解360纳米AI搜索的核心功能。提供官方入口、使用技巧、优缺点分析，以及如何利用它进行高效检索和创作。',
    seoKeywords: ['纳米AI搜索', '360AI', '纳米搜索', 'AI搜索引擎'],
    overview: '纳米AI搜索将传统搜索与大模型能力相结合，通过智能分析和多模态理解，为用户提供直接的答案和创作辅助，极大提升了获取和处理信息的效率。',
    features: ['智能问答', '多模态搜索', '文档分析', 'PPT生成', '多模态智能体'],
    useCases: ['日常资料检索', '学术与行业报告分析', '内容创作与灵感收集', '办公文档快速生成'],
    gettingStarted: '访问官网或下载APP，登录360账号即可开始使用AI搜索和创作功能。',
    networkAndRegion: '无需特殊网络环境，国内直接访问。',
    advantages: ['依托360搜索多年的数据积累，中文搜索体验优秀', '多模态能力丰富，支持语音和图片搜索', '集成大量实用智能体工具'],
    limitations: ['部分高级功能可能需要额度限制', '专业技术领域的搜索深度仍有提升空间'],
    faq: [
      { q: '纳米AI搜索完全免费吗？', a: '基础搜索和问答功能是免费的，部分深度生成工具可能有次数限制。' },
      { q: '支持手机端吗？', a: '是的，提供iOS、Android和鸿蒙原生版本应用。' }
    ],
    alternatives: ['kimi', 'metaso', 'tiangong']
  },
  {
    slug: 'wps-ai',
    name: 'WPS AI',
    company: '金山办公',
    officialUrl: 'https://ai.wps.cn/',
    category: 'productivity',
    categories: ['productivity', 'chat'],
    region: 'china',
    shortDescription: '内置于WPS Office的AI办公助手，全面提升文档创作与处理效率。',
    description: 'WPS AI是金山办公旗下内置于WPS Office中的人工智能应用，提供包括智能文档写作、长文处理、一键生成PPT、表格数据分析及自然语言交互等多种功能，致力于重塑现代办公体验。',
    tags: ['AI办公', 'WPS', '文档处理', 'PPT生成', '表格分析'],
    featured: true,
    freePlan: 'limited',
    pricingType: 'freemium',
    chineseSupport: 'native',
    accountRequired: 'yes',
    platforms: ['windows', 'mac', 'web', 'ios', 'android'],
    bestFor: '经常处理Word、Excel、PPT的职场人士和学生',
    lastUpdated: '2026-09-15',
    seoTitle: 'WPS AI 官方入口与使用指南：让办公文档处理更智能',
    seoDescription: '全面解析WPS AI的功能与使用方法，包含智能写作、PPT一键生成和表格分析等。了解如何通过WPS AI提升日常办公效率。',
    seoKeywords: ['WPS AI', 'AI办公', '金山办公AI', 'PPT生成', 'AI文档'],
    overview: 'WPS AI深度整合在日常办公套件中，通过大模型能力，用户无需切换工具即可在文档、表格和演示中直接唤起AI，实现内容的自动生成和深度分析。',
    features: ['智能文档写作与润色', '一键生成PPT幻灯片', '复杂表格数据智能分析', 'PDF长文总结与问答', '语音交互与排版优化'],
    useCases: ['快速撰写公文、总结和报告', '从零开始自动生成演示文稿大纲与页面', '提取超长PDF文档的核心观点', '用自然语言完成复杂的Excel数据计算'],
    gettingStarted: '将WPS Office升级到最新版本，在软件顶部菜单栏或编辑区内点击WPS AI图标即可启用。',
    networkAndRegion: '国内直接访问，网络连接稳定。',
    advantages: ['无缝集成于国民级办公软件中', '中文语境下的排版和格式处理极佳', '极大地降低了复杂办公软件的使用门槛'],
    limitations: ['高级AI权益需要单独订阅WPS超级会员Pro等付费计划', '复杂逻辑生成的准确度需人工复核'],
    faq: [
      { q: 'WPS AI需要单独下载吗？', a: '不需要，WPS AI已经内置在最新版的WPS Office客户端中，直接更新软件即可。' },
      { q: '使用WPS AI要收费吗？', a: '有基础免费体验额度，但长期高频使用或高级功能需购买相应的WPS会员。' }
    ],
    alternatives: ['notion-ai', 'doubao', 'kimi']
  },
  {
    slug: 'openai-codex',
    name: 'OpenAI Codex',
    company: 'OpenAI',
    officialUrl: 'https://openai.com/index/openai-codex',
    category: 'coding',
    categories: ['coding'],
    region: 'global',
    shortDescription: '将自然语言转化为代码的强大AI模型，驱动了GitHub Copilot等工具。',
    description: 'OpenAI Codex是OpenAI开发的人工智能模型，它能够解析自然语言并生成代码。作为驱动GitHub Copilot的底层技术，Codex精通数十种编程语言，能够帮助开发者快速完成代码片段编写、代码重构和文档生成。',
    tags: ['编程', '代码生成', 'OpenAI', 'Copilot底层模型'],
    featured: false,
    freePlan: 'no',
    pricingType: 'paid',
    chineseSupport: 'supported',
    accountRequired: 'yes',
    platforms: ['api', 'web'],
    bestFor: '需要强大代码生成能力的开发者和企业级API使用者',
    lastUpdated: '2026-09-15',
    seoTitle: 'OpenAI Codex：强大的自然语言转代码模型解析',
    seoDescription: '深入了解驱动GitHub Copilot的OpenAI Codex模型。探索其代码生成能力、支持语言、API使用方法及其在开发工作流中的应用。',
    seoKeywords: ['OpenAI Codex', 'Codex模型', 'AI代码生成', '编程模型'],
    overview: 'Codex 是 GPT-3 的后代，经过大量公共源代码库的微调，它的出现标志着 AI 辅助编程进入了实质性可用阶段。',
    features: ['自然语言转代码', '跨多语言支持（Python、JS等）', '代码解释与注释生成', 'API接口调用集成'],
    useCases: ['通过API构建自定义编程助手', '在IDE中实现智能代码补全', '自动化脚本编写', '代码语言翻译'],
    gettingStarted: '目前普通用户主要通过 GitHub Copilot 体验其能力，企业和开发者可通过 OpenAI API 申请访问相关模型能力（目前部分能力已由 GPT-4 替代）。',
    networkAndRegion: '国内无法直接访问，需要国际网络环境或专线支持。',
    advantages: ['代码理解能力极强，支持众多主流语言', '能够理解上下文并生成大段连贯代码', '背后依托 OpenAI 强大的模型迭代能力'],
    limitations: ['直接的 Codex API 已逐步被更先进的通用 GPT-4 模型取代', '生成代码偶尔存在安全或逻辑漏洞，需人工审查'],
    faq: [
      { q: '怎么直接使用 Codex？', a: '对于普通用户，最直接的方式是使用基于其衍生技术开发的 GitHub Copilot 插件。' },
      { q: 'Codex 和 GPT-4 在编程上有什么区别？', a: 'Codex 是早期专门针对代码训练的模型，而目前的 GPT-4 等模型已经内化并超越了早期 Codex 的编程能力。' }
    ],
    alternatives: ['copilot', 'cursor', 'claude']
  },
  {
    slug: 'jetbrains-ai',
    name: 'JetBrains AI',
    company: 'JetBrains',
    officialUrl: 'https://www.jetbrains.com/ai/',
    category: 'coding',
    categories: ['coding', 'productivity'],
    region: 'global',
    shortDescription: '深度集成于JetBrains全系IDE的智能编程助手。',
    description: 'JetBrains AI Assistant 是由著名开发工具厂商 JetBrains 推出的 AI 服务，它深度无缝地集成在 IntelliJ IDEA、PyCharm、WebStorm 等全系 IDE 中，提供代码解释、重构建议、单元测试生成和提交信息编写等全方位开发辅助。',
    tags: ['编程', 'IDE集成', 'JetBrains', 'AI代码生成'],
    featured: false,
    freePlan: 'limited',
    pricingType: 'paid',
    chineseSupport: 'supported',
    accountRequired: 'yes',
    platforms: ['windows', 'mac', 'linux'],
    bestFor: '已经在使用JetBrains IDE系列软件的职业开发者',
    lastUpdated: '2026-09-15',
    seoTitle: 'JetBrains AI Assistant：深度集成IDE的编程助手测评',
    seoDescription: '了解JetBrains AI Assistant的功能特色、价格及使用方法。作为JetBrains全系IDE的原生插件，它如何改变开发者的日常编码体验。',
    seoKeywords: ['JetBrains AI', 'AI Assistant', 'IDEA AI', '代码重构AI'],
    overview: '由于 JetBrains 对其自家 IDE 架构的深刻理解，其 AI Assistant 能够比外部插件获取更准确的代码上下文，从而给出更符合项目结构的智能建议。',
    features: ['多轮上下文对话', '代码解释与重构', '自动化生成提交信息（Commit Message）', '文档与单元测试一键生成', '错误解析辅助'],
    useCases: ['在阅读遗留代码时快速获取解释', '一键生成符合规范的代码注释', '根据当前代码上下文快速生成测试用例', '修复复杂的编译报错'],
    gettingStarted: '在受支持的 JetBrains IDE 版本中，开启 AI Assistant 插件并登录拥有相关订阅的 JetBrains 账号即可使用。',
    networkAndRegion: '中国大陆地区的服务由特定的合规模型驱动，国际版则接入多种先进大模型（如OpenAI等），需根据账号区域判断可用性。',
    advantages: ['作为官方原生插件，IDE 深度集成体验无可比拟', '能够感知整个项目的结构和类关系', '支持多种大型语言模型后端的智能路由'],
    limitations: ['需要订阅 JetBrains AI 服务（单独计费）', '国内区域的服务与国际版模型存在差异'],
    faq: [
      { q: 'JetBrains AI 和 GitHub Copilot 哪个好？', a: 'Copilot 在自动补全上响应极快，而 JetBrains AI 在对代码进行复杂重构和解释时，由于更懂 IDE 结构，通常表现更优。' },
      { q: '可以免费使用吗？', a: '提供有限的免费试用期，之后需要订阅 Pro 计划购买。' }
    ],
    alternatives: ['copilot', 'cursor', 'tabnine']
  },
  {
    slug: 'jasper',
    name: 'Jasper',
    company: 'Jasper AI',
    officialUrl: 'https://www.jasper.ai/',
    category: 'productivity',
    categories: ['productivity', 'chat'],
    region: 'global',
    shortDescription: '专为企业和营销团队打造的高级AI内容创作平台。',
    description: 'Jasper (前身为 Jarvis) 是一款领先的 AI 内容生成器，专为企业营销、广告文案、博客撰写和社交媒体运营设计。它能够学习品牌的专属语调，并快速批量生成高度转化的高质量原创内容。',
    tags: ['营销', '文案创作', '内容生成', '品牌语调'],
    featured: false,
    freePlan: 'no',
    pricingType: 'paid',
    chineseSupport: 'supported',
    accountRequired: 'yes',
    platforms: ['web', 'browser-extension'],
    bestFor: '营销团队、广告文案人员、自媒体运营者及企业内容创作者',
    lastUpdated: '2026-09-15',
    seoTitle: 'Jasper AI：企业级AI营销内容创作平台介绍',
    seoDescription: '全面解析Jasper AI的功能、价格及在企业营销中的应用。了解如何使用Jasper生成符合品牌语调的博客、广告及社交媒体文案。',
    seoKeywords: ['Jasper AI', 'AI营销文案', 'AI内容生成', 'AI写作工具'],
    overview: 'Jasper 并非仅仅是另一个套壳对话机器人，它针对营销流程进行了深度定制，提供了大量的成熟模板和工作流集成，极大地提升了内容生产的效率与标准化。',
    features: ['50+ 营销文案模板', '品牌声音(Brand Voice)学习功能', 'Jasper Chat 对话模式', '浏览器插件与API集成', '支持生成配套图像 (Jasper Art)'],
    useCases: ['撰写 SEO 优化的博客长文', '快速生成多组 Facebook/Google 广告文案', '构思吸引人的社交媒体帖子和邮件营销文案', '制定品牌内容矩阵策略'],
    gettingStarted: '访问官网注册账号，通过提供的主题模板或直接在文档编辑器中输入指令生成内容。',
    networkAndRegion: '国内需通过科学上网环境访问。',
    advantages: ['极度专注营销领域，模板丰富且专业', '能够设定并记忆独特的品牌语调', '支持团队协作和项目管理功能'],
    limitations: ['价格相对高昂，适合有预算的企业团队', '对中文的高级修辞支持偶尔不如英文原生自然'],
    faq: [
      { q: 'Jasper 和 ChatGPT 有什么不同？', a: 'ChatGPT 是通用对话助手，而 Jasper 针对营销场景深度优化，提供更多定制化模板、品牌语调管理和团队协作功能。' },
      { q: '支持中文写作吗？', a: '支持包括中文在内的几十种语言，表现良好。' }
    ],
    alternatives: ['copy-ai', 'writesonic', 'chatgpt']
  },
  {
    slug: 'copy-ai',
    name: 'Copy.ai',
    company: 'CopyAI',
    officialUrl: 'https://www.copy.ai/',
    category: 'productivity',
    categories: ['productivity', 'chat'],
    region: 'global',
    shortDescription: '简单易用的AI文案写作与销售自动化平台。',
    description: 'Copy.ai 是一款深受营销人员喜爱的 AI 写作工具，专注于解决文案创作中的“空白页焦虑”。近年来，它不仅提供基础的内容生成，还转型为 GTM（走向市场）自动化平台，帮助销售和营销团队自动化从线索跟进到内容发布的整个流程。',
    tags: ['文案创作', '销售自动化', '营销', 'AI写作'],
    featured: false,
    freePlan: 'yes',
    pricingType: 'freemium',
    chineseSupport: 'supported',
    accountRequired: 'yes',
    platforms: ['web'],
    bestFor: '需要快速产出短文案的营销人员及追求流程自动化的销售团队',
    lastUpdated: '2026-09-15',
    seoTitle: 'Copy.ai：智能文案创作与营销自动化利器',
    seoDescription: '了解Copy.ai如何帮助团队快速生成社交媒体帖子、邮件和博客内容，以及其最新推出的销售与营销工作流自动化功能。',
    seoKeywords: ['Copy.ai', 'AI文案生成', '营销自动化', 'AI写作'],
    overview: '相比其他复杂的企业工具，Copy.ai 以其极简的界面和即时的免费体验吸引了大量早期用户，非常适合快速产出灵感。',
    features: ['海量短文案模板', 'Workflows 自动化工作流', '多语言支持', 'Infobase 企业信息库', '品牌声音(Brand Voice)'],
    useCases: ['生成Instagram和Twitter推文灵感', '自动化个性化冷邮件（Cold Email）外发', '重写或扩写现有段落', '生成产品描述和广告标题'],
    gettingStarted: '在官网免费注册后，选择所需的工具模板输入几个关键词即可生成多个文案选项。',
    networkAndRegion: '国内需通过科学上网环境访问。',
    advantages: ['界面极其直观，上手零门槛', '提供永久免费计划（限制字数/字符数）', '强大的自动化 Workflow 能够连接多个外部应用'],
    limitations: ['在超长深度文章的连贯性上略逊于部分专业长文生成工具', '高级功能如工作流和品牌声音需付费'],
    faq: [
      { q: 'Copy.ai 完全免费吗？', a: '它提供一个永久免费计划，包含基本的聊天功能和每月有限的生成字数，适合个人轻度使用。' },
      { q: 'Copy.ai 和 Jasper 怎么选？', a: '如果追求极速生成短文案和免费白嫖，Copy.ai 更好；如果需要专业的长文撰写和复杂的团队管理，Jasper 更强。' }
    ],
    alternatives: ['jasper', 'writesonic', 'chatgpt']
  },
  {
    slug: 'writesonic',
    name: 'Writesonic',
    company: 'Writesonic',
    officialUrl: 'https://writesonic.com/',
    category: 'productivity',
    categories: ['productivity', 'search', 'chat'],
    region: 'global',
    shortDescription: '结合实时搜索的高效AI写作与SEO内容平台。',
    description: 'Writesonic 是一款综合性的 AI 内容创建平台，不仅支持高质量的文章生成，还特别注重 SEO 优化和实时数据整合。其内置的 Chatsonic 是一个强大的对话式 AI，能够获取最新网络信息，成为内容创作者的重要助手。',
    tags: ['AI写作', 'SEO优化', '实时搜索', 'Chatsonic'],
    featured: false,
    freePlan: 'yes',
    pricingType: 'freemium',
    chineseSupport: 'supported',
    accountRequired: 'yes',
    platforms: ['web', 'browser-extension'],
    bestFor: 'SEO专家、博主以及需要结合最新资讯进行写作的内容创作者',
    lastUpdated: '2026-09-15',
    seoTitle: 'Writesonic & Chatsonic：实时联网的SEO与内容AI工具',
    seoDescription: '评测Writesonic强大的AI写作与SEO功能，并介绍能够实时搜索网络信息的Chatsonic，了解它为何是博主和营销人员的优选。',
    seoKeywords: ['Writesonic', 'Chatsonic', 'AI SEO写作', 'AI文章生成器'],
    overview: 'Writesonic 的核心竞争力在于其对 SEO 极度友好，能够生成符合搜索引擎喜好排版的长篇博客，并配合实时网络数据保证内容的时效性。',
    features: ['AI Article Writer (长文生成)', 'Chatsonic (实时联网对话助手)', 'Botsonic (定制化AI客服构建器)', 'SEO 工具深度集成', '文本转语音及图像生成 (Photosonic)'],
    useCases: ['撰写高度 SEO 优化的 2000 字以上博客文章', '利用 Chatsonic 调查最新的行业新闻和趋势', '一键生成 Landing Page (落地页) 结构文案', '电商平台产品批量描述生成'],
    gettingStarted: '注册账号后可获得免费字数额度，选择特定的模板（如Article Writer 6.0）开始结构化创作。',
    networkAndRegion: '国内需通过科学上网环境访问。',
    advantages: ['自带实时联网搜索能力，确保内容非过时信息', '文章生成流程清晰（从关键词、标题、大纲到正文）', '整合了多种功能（文本、图像、客服机器人）性价比高'],
    limitations: ['基于额度（字数/词数）计费，长文生成消耗较快', '生成的文章有时具有明显的模板化特征，需要人工润色'],
    faq: [
      { q: 'Chatsonic 是什么？', a: 'Chatsonic 是 Writesonic 平台内置的对话机器人，类似 ChatGPT，但原生支持实时网络搜索和图像生成。' },
      { q: 'Writesonic 生成的内容能通过 AI 检测吗？', a: '平台提供了相关的功能以尽量使其自然，但没有任何工具能 100% 保证绕过严格的 AI 检测，人工审查仍是必要的。' }
    ],
    alternatives: ['jasper', 'copy-ai', 'perplexity']
  },`);

fs.writeFileSync('src/data/aiTools.ts', c);
